name: learn-github-actions
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  deploy-web:
    needs: [git-clone,clean-web-server]
    runs-on: ubuntu-latest
    steps:
      - name: 部署前端
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HUAWEI_USERNAME }}
          password: ${{ secrets.HUAWEI_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            cd /home/solution-box/web/web-next/
            pnpm install
            pnpm run build
            sudo nohup pnpm run start > /home/solution-box/web.log 2>&1 &
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 配置node语言环境
        uses: actions/setup-node@v3.5.1
        with:
          go-version: 1.16
          check-latest: true
          cache: true
          cache-dependency-path: server/go/go.sum

      - name: 构建程序
        run:  npm run build

      - name: 向服务器传输可执行程序
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}  
          username: ${{ secrets.HUAWEI_USERNAME }} 
          port: ${{ secrets.SSH_PORT }} 
          password: ${{ secrets.HUAWEI_PASSWORD }}
          source: "./dist/*" 
          target: "/usr/share/nginx/html/bookRoom"
          strip_components: 2
          overwrite: true
