name: 部署book_reader项目
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 配置node语言环境
        uses: actions/setup-node@v3.5.1
        with:
          ndoe-version: 16.3.1
          cache: yarn

      - name: 构建程序
        run:  yarn && yarn build

      - name: 向服务器传输可执行程序
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}  
          username: ${{ secrets.HUAWEI_USERNAME }} 
          port: ${{ secrets.SSH_PORT }} 
          password: ${{ secrets.HUAWEI_PASSWORD }}
          source: "./build/*" 
          target: "/usr/share/nginx/html/bookRoom"
          strip_components: 2
          overwrite: true
