name: learn-github-actions
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  clean-web-server:
    runs-on: ubuntu-latest
    steps:
      - name: 结束前后端旧的进程
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HUAWEI_USERNAME }}
          password: ${{ secrets.HUAWEI_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            ps -aux|grep 'pnpm\|node'|grep -v grep| awk '{print $2}'| xargs kill
  git-clone:
    runs-on: ubuntu-latest
    steps:
      - name: 下载最新文件
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HUAWEI_USERNAME }}
          password: ${{ secrets.HUAWEI_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            cd /home/solution-box/
            git pull
  deploy-web:
    needs: [git-clone,clean-web-server]
    runs-on: ubuntu-latest
    steps:
      - name: 部署前端
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HUAWEI_USERNAME }}
          password: ${{ secrets.HUAWEI_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            cd /home/solution-box/web/web-next/
            pnpm install
            pnpm run build
            sudo nohup pnpm run start > /home/solution-box/web.log 2>&1 &
